defaults
{
    instances       = 50
    per_source      = 10
    cps             = 30 10
    log_type        = SYSLOG daemon
    log_on_success  = PID HOST EXIT
    log_on_failure  = HOST
}

includedir /etc/xinetd.d
