# /etc/xinetd.conf
defaults
{
    log_type        = SYSLOG daemon
    log_on_failure  = HOST
    log_on_success  = PID HOST DURATION EXIT
    cps             = 30 10
    instances       = 50
    per_source      = 5
}

includedir /etc/xinetd.d
